import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Outfit } from "next/font/google";
import "tailwindcss";
// import { ClerkProvider } from "@clerk/nextjs";
import ClerkLayout from "./components/clerklayout";
import Provider from "./provider";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const outfit = Outfit({ subsets: ["latin"] });
export default function RootLayout({ children }) {
  return (
    <ClerkLayout>
      <html lang="en">
        <body className={outfit.className}>
          <Provider>{children}</Provider>
        </body>
      </html>
    </ClerkLayout>
  );
}
